### ISSUE TITLE
Agent can stop watching for namespace changes

### ISSUE THREAD

**Issue by tomdee** [projectcalico/k8s-policy#15]
Seen on current master code

```
2016-03-24 21:19:11,823 6 INFO Configuring /etc/hosts
2016-03-24 21:19:11,823 6 INFO Appended 'kubernetes.default  -> 10.3.0.1' to /etc/hosts
2016-03-24 21:19:11,824 6 INFO Beginning execution
2016-03-24 21:19:11,824 6 INFO Setting NetworkPolicy ADDED handler: <function add_update_network_policy at 0x7fca6253c050>
2016-03-24 21:19:11,824 6 INFO Setting NetworkPolicy DELETED handler: <function delete_network_policy at 0x7fca67402c80>
2016-03-24 21:19:11,824 6 INFO Setting Namespace ADDED handler: <function add_update_namespace at 0x7fca62543848>
2016-03-24 21:19:11,825 6 INFO Setting Namespace DELETED handler: <function delete_namespace at 0x7fca62543938>
2016-03-24 21:19:11,825 6 INFO Setting Pod ADDED handler: <function add_update_pod at 0x7fca62543a28>
2016-03-24 21:19:11,825 6 INFO Setting Pod DELETED handler: <function delete_pod at 0x7fca62543b18>
2016-03-24 21:19:11,834 6 INFO Getting existing NetworkPolicy objects
2016-03-24 21:19:11,835 6 INFO Getting API resources 'https://kubernetes.default:443/apis/net.alpha.kubernetes.io/v1alpha1/networkpolicys' at version 'None'. stream=False
2016-03-24 21:19:11,907 6 INFO Response: <Response [200]>
2016-03-24 21:19:11,908 6 INFO 0 existing NetworkPolicy(s)
2016-03-24 21:19:11,908 6 INFO Started watch on: NetworkPolicy
2016-03-24 21:19:11,908 6 INFO Getting existing Namespace objects
2016-03-24 21:19:11,908 6 INFO Getting API resources 'https://kubernetes.default:443/api/v1/namespaces' at version 'None'. stream=False
2016-03-24 21:19:11,911 6 INFO Starting watch on path: https://kubernetes.default:443/apis/net.alpha.kubernetes.io/v1alpha1/watch/networkpolicys
2016-03-24 21:19:11,911 6 INFO Getting API resources 'https://kubernetes.default:443/apis/net.alpha.kubernetes.io/v1alpha1/watch/networkpolicys' at version 'None'. stream=True
2016-03-24 21:19:11,974 6 INFO Response: <Response [200]>
2016-03-24 21:19:11,975 6 INFO 3 existing Namespace(s)
2016-03-24 21:19:11,975 6 INFO Started watch on: Namespace
2016-03-24 21:19:11,975 6 INFO Getting existing Pod objects
2016-03-24 21:19:11,975 6 INFO Getting API resources 'https://kubernetes.default:443/api/v1/pods' at version 'None'. stream=False
2016-03-24 21:19:11,977 6 INFO Starting watch on path: https://kubernetes.default:443/api/v1/watch/namespaces
2016-03-24 21:19:11,978 6 INFO Getting API resources 'https://kubernetes.default:443/api/v1/watch/namespaces' at version '1370'. stream=True
2016-03-24 21:19:12,058 6 INFO Response: <Response [200]>
2016-03-24 21:19:12,064 6 INFO 11 existing Pod(s)
2016-03-24 21:19:12,065 6 INFO Started watch on: Pod
2016-03-24 21:19:12,066 6 INFO Adding/updating namespace: (None, u'calico-system')
2016-03-24 21:19:12,066 6 INFO Namespace (None, u'calico-system') has network-isolation? False
2016-03-24 21:19:12,067 6 INFO Starting watch on path: https://kubernetes.default:443/api/v1/watch/pods
2016-03-24 21:19:12,067 6 INFO Getting API resources 'https://kubernetes.default:443/api/v1/watch/pods' at version '1370'. stream=True
2016-03-24 21:19:12,099 6 INFO Created/updated profile for namespace calico-system
2016-03-24 21:19:12,100 6 INFO Adding/updating namespace: (None, u'default')
2016-03-24 21:19:12,100 6 INFO Namespace (None, u'default') has network-isolation? False
2016-03-24 21:19:12,149 6 INFO Created/updated profile for namespace default
2016-03-24 21:19:12,150 6 INFO Adding/updating namespace: (None, u'kube-system')
2016-03-24 21:19:12,150 6 INFO Namespace (None, u'kube-system') has network-isolation? False
2016-03-24 21:19:12,195 6 INFO Created/updated profile for namespace kube-system
2016-03-24 21:19:12,196 6 INFO Adding new pod: (u'calico-system', u'calico-policy-agent-iao9c')
2016-03-24 21:19:12,212 6 INFO Updated labels on pod (u'calico-system', u'calico-policy-agent-iao9c')
2016-03-24 21:19:12,235 6 INFO Adding new pod: (u'kube-system', u'heapster-v10-jzllz')
2016-03-24 21:19:12,316 6 INFO Updated labels on pod (u'kube-system', u'heapster-v10-jzllz')
2016-03-24 21:19:12,326 6 INFO Adding new pod: (u'kube-system', u'kube-apiserver-172.17.4.101')
2016-03-24 21:19:12,330 6 WARNING No endpoint for 'kube-system.kube-apiserver-172.17.4.101', wait until running
2016-03-24 21:19:12,332 6 INFO Adding new pod: (u'kube-system', u'kube-controller-manager-172.17.4.101')
2016-03-24 21:19:12,335 6 WARNING No endpoint for 'kube-system.kube-controller-manager-172.17.4.101', wait until running
2016-03-24 21:19:12,337 6 INFO Adding new pod: (u'kube-system', u'kube-dns-v9-pivqg')
2016-03-24 21:19:12,357 6 INFO Updated labels on pod (u'kube-system', u'kube-dns-v9-pivqg')
2016-03-24 21:19:12,431 6 INFO Adding new pod: (u'kube-system', u'kube-podmaster-172.17.4.101')
2016-03-24 21:19:12,438 6 WARNING No endpoint for 'kube-system.kube-podmaster-172.17.4.101', wait until running
2016-03-24 21:19:12,439 6 INFO Adding new pod: (u'kube-system', u'kube-proxy-172.17.4.101')
2016-03-24 21:19:12,443 6 WARNING No endpoint for 'kube-system.kube-proxy-172.17.4.101', wait until running
2016-03-24 21:19:12,444 6 INFO Adding new pod: (u'kube-system', u'kube-proxy-172.17.4.201')
2016-03-24 21:19:12,448 6 WARNING No endpoint for 'kube-system.kube-proxy-172.17.4.201', wait until running
2016-03-24 21:19:12,449 6 INFO Adding new pod: (u'kube-system', u'kube-proxy-172.17.4.202')
2016-03-24 21:19:12,457 6 WARNING No endpoint for 'kube-system.kube-proxy-172.17.4.202', wait until running
2016-03-24 21:19:12,458 6 INFO Adding new pod: (u'kube-system', u'kube-scheduler-172.17.4.101')
2016-03-24 21:19:12,462 6 WARNING No endpoint for 'kube-system.kube-scheduler-172.17.4.101', wait until running
2016-03-24 21:19:12,463 6 INFO Adding new pod: (u'kube-system', u'monitoring-influxdb-v2-aoz5g')
2016-03-24 21:19:12,477 6 INFO Updated labels on pod (u'kube-system', u'monitoring-influxdb-v2-aoz5g')
2016-03-24 21:48:45,472 6 INFO Adding new pod: (u'calico-system', u'calico-policy-agent-iao9c')
2016-03-24 21:48:46,058 6 INFO Updated labels on pod (u'calico-system', u'calico-policy-agent-iao9c')
2016-03-24 21:48:46,450 6 INFO Adding new pod: (u'kube-system', u'monitoring-influxdb-v2-aoz5g')
2016-03-24 21:48:47,002 6 INFO Updated labels on pod (u'kube-system', u'monitoring-influxdb-v2-aoz5g')
2016-03-24 21:48:47,352 6 INFO Adding new pod: (u'kube-system', u'heapster-v10-jzllz')
2016-03-24 21:48:47,684 6 INFO Updated labels on pod (u'kube-system', u'heapster-v10-jzllz')
2016-03-24 21:48:48,083 6 INFO Adding new pod: (u'kube-system', u'monitoring-influxdb-v2-aoz5g')
2016-03-24 21:48:48,452 6 INFO Updated labels on pod (u'kube-system', u'monitoring-influxdb-v2-aoz5g')
2016-03-24 21:48:48,765 6 INFO Adding new pod: (u'calico-system', u'calico-policy-agent-iao9c')
2016-03-24 21:48:49,182 6 INFO Updated labels on pod (u'calico-system', u'calico-policy-agent-iao9c')
2016-03-24 21:48:49,502 6 INFO Adding new pod: (u'kube-system', u'heapster-v10-jzllz')
2016-03-24 21:48:49,765 6 INFO Updated labels on pod (u'kube-system', u'heapster-v10-jzllz')
2016-03-24 21:48:50,148 6 INFO Adding new pod: (u'kube-system', u'kube-proxy-172.17.4.202')
2016-03-24 21:48:50,372 6 WARNING No endpoint for 'kube-system.kube-proxy-172.17.4.202', wait until running
2016-03-24 21:58:01,955 6 INFO Getting API resources 'https://kubernetes.default:443/api/v1/watch/namespaces' at version '1370'. stream=True
2016-03-24 21:58:02,002 6 ERROR Invalid update: (u'ERROR', u'Status', {u'status': u'Failure', u'kind': u'Status', u'message': u'401: The event in requested index is outdated and cleared (the requested history has been cleared [1625/1371]) [2624]', u'apiVersion': u'v1', u'metadata': {}})
Traceback (most recent call last):
  File "<string>", line 187, in read_updates
  File "<string>", line 200, in _process_update
KeyError: 'name'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 801, in __bootstrap_inner
  File "threading.py", line 754, in run
  File "<string>", line 260, in _watch_api
KeyError: 'resourceVersion'

2016-03-24 22:01:19,513 6 INFO Adding new pod: (u'default', u'busybox-42uqg')
2016-03-24 22:01:19,518 6 WARNING No endpoint for 'default.busybox-42uqg', wait until running
2016-03-24 22:01:19,546 6 INFO Adding new pod: (u'default', u'busybox-42uqg')
2016-03-24 22:01:19,551 6 WARNING No endpoint for 'default.busybox-42uqg', wait until running
2016-03-24 22:01:19,646 6 INFO Adding new pod: (u'default', u'busybox-42uqg')
2016-03-24 22:01:19,651 6 WARNING No endpoint for 'default.busybox-42uqg', wait until running
2016-03-24 22:01:25,793 6 INFO Adding new pod: (u'default', u'busybox-42uqg')
2016-03-24 22:01:25,804 6 INFO Updated labels on pod (u'default', u'busybox-42uqg')
2016-03-24 22:01:25,985 6 INFO Adding new pod: (u'default', u'busybox-42uqg')
2016-03-24 22:01:26,001 6 INFO Updated labels on pod (u'default', u'busybox-42uqg')
2016-03-24 22:02:42,373 6 INFO Adding new pod: (u'default', u'busybox2-kmuoo')
2016-03-24 22:02:42,379 6 WARNING No endpoint for 'default.busybox2-kmuoo', wait until running
2016-03-24 22:02:42,402 6 INFO Adding new pod: (u'default', u'busybox2-kmuoo')
2016-03-24 22:02:42,407 6 WARNING No endpoint for 'default.busybox2-kmuoo', wait until running
2016-03-24 22:02:42,633 6 INFO Adding new pod: (u'default', u'busybox2-kmuoo')
2016-03-24 22:02:42,638 6 WARNING No endpoint for 'default.busybox2-kmuoo', wait until running
2016-03-24 22:02:45,461 6 INFO Adding new pod: (u'default', u'busybox-42uqg')
2016-03-24 22:02:45,472 6 INFO Updated labels on pod (u'default', u'busybox-42uqg')
2016-03-24 22:02:47,273 6 INFO Adding new pod: (u'default', u'busybox2-kmuoo')
2016-03-24 22:02:47,283 6 INFO Updated labels on pod (u'default', u'busybox2-kmuoo')
2016-03-24 22:02:47,432 6 INFO Adding new pod: (u'default', u'busybox2-kmuoo')
2016-03-24 22:02:47,441 6 INFO Updated labels on pod (u'default', u'busybox2-kmuoo')
2016-03-24 22:02:55,148 6 INFO Adding new pod: (u'default', u'busybox-42uqg')
2016-03-24 22:02:55,159 6 INFO Updated labels on pod (u'default', u'busybox-42uqg')
2016-03-24 22:03:37,375 6 INFO Adding new pod: (u'default', u'busybox2-kmuoo')
2016-03-24 22:03:37,388 6 INFO Updated labels on pod (u'default', u'busybox2-kmuoo')
2016-03-24 22:03:47,267 6 INFO Adding new pod: (u'default', u'busybox2-kmuoo')
2016-03-24 22:03:47,277 6 INFO Updated labels on pod (u'default', u'busybox2-kmuoo')
2016-03-24 22:08:02,906 6 INFO Getting API resources 'https://kubernetes.default:443/apis/net.alpha.kubernetes.io/v1alpha1/watch/networkpolicys' at version 'None'. stream=True

```

**Comment by microadam** [comment]
Have also seen this in my setup
