### ISSUE TITLE
policy agent ETCD_ENDPOINTS have to be IPs or FQDNs

### ISSUE THREAD

**Issue by lwr20** [projectcalico/k8s-policy#23]
If you specify etcd endpoints for the policy agent using unqualified domain names, the policy agent crashes with logs like:

```
$ kubectl logs calico-policy-agent-127.0.0.1 --namespace=calico-system k8s-policy-agent
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "handlers/network_policy.py", line 11, in <module>
  File "site-packages/pycalico/datastore.py", line 246, in __init__
  File "site-packages/etcd/client.py", line 204, in __init__
  File "site-packages/etcd/client.py", line 299, in machines
  File "site-packages/etcd/client.py", line 299, in machines
  File "site-packages/etcd/client.py", line 301, in machines
etcd.EtcdException: Could not get the list of servers, maybe you provided the wrong host(s) to connect to?
policy_agent returned -1
```

It seems that the policy-agent container is based on alpine linux and alpine linux does not support the search or domain options in resolv.conf.  See: https://bugs.alpinelinux.org/issues/469

**Comment by lwr20** [comment]
@caseydavenport did I miss anything out?

**Comment by djosborne** [comment]
If anyone wants to test the fix, use: `quay.io/calico/k8s-policy-agent:djosborne-patch-1`
