### ISSUE TITLE
how to deploy k8s-policy

### ISSUE THREAD

**Issue by timchenxiaoyu** [projectcalico/k8s-policy#62]
my k8s is 1.2 and calico 1.3.1?how to deploy this

**Comment by caseydavenport** [comment]
@timchenxiaoyu The k8s NetworkPolicy API was introduced in k8s v1.3.0, so you'll need at least that Kubernetes version in order to use the Calico policy controller.

If you upgrade Kubernetes, I'd recommend looking at the Calico installation documentation for k8s, which can be found here: http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/

**Comment by timchenxiaoyu** [comment]
I upgrade k8s to 1.3 and setup policy-controller.yaml but err
raceback (most recent call last):
  File "<string>", line 295, in _manage_resource
  File "<string>", line 400, in _sync_resources
TypeError: object of type 'NoneType' has no len()
2016-12-11 01:58:19,939 20 WARNING Re-starting watch on resource: NetworkPolicy

**Comment by caseydavenport** [comment]
@timchenxiaoyu have you checked to see if policy is working?

That error seems to be because Kubernetes is retuning None instead of an empty list.  The policy controller should just retry and succeed eventually.

**Comment by timchenxiaoyu** [comment]
kube-policy-controller:v0.3.0

**Comment by caseydavenport** [comment]
Any reason you need to use such an old version?

**Comment by timchenxiaoyu** [comment]
my env is：
calicoctl version
0.22.0
./calico -v
"Version": "v1.3.1", 
kubectl version
{Major:"1", Minor:"3", GitVersion:"v1.3.2+9bafa34", 

has this error：

kubectl version
2016-12-16 02:40:03,940 5 WARNING Re-starting watch on resource: NetworkPolicy
2016-12-16 02:40:03,975 5 INFO Syncing 'Pod' objects
2016-12-16 02:40:03,976 5 INFO Syncing 'Namespace' objects
2016-12-16 02:40:03,984 5 ERROR Unahandled exception killed Pod manager
Traceback (most recent call last):
  File "<string>", line 295, in _manage_resource
  File "<string>", line 386, in _sync_resources
  File "site-packages/requests/models.py", line 808, in json
  File "site-packages/simplejson/__init__.py", line 516, in loads
  File "site-packages/simplejson/decoder.py", line 370, in decode
  File "site-packages/simplejson/decoder.py", line 400, in raw_decode
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2016-12-16 02:40:03,984 5 WARNING Re-starting watch on resource: Pod
2016-12-16 02:40:03,989 5 ERROR Unahandled exception killed Namespace manager
Traceback (most recent call last):
  File "<string>", line 295, in _manage_resource
  File "<string>", line 386, in _sync_resources
  File "site-packages/requests/models.py", line 808, in json
  File "site-packages/simplejson/__init__.py", line 516, in loads
  File "site-packages/simplejson/decoder.py", line 370, in decode
  File "site-packages/simplejson/decoder.py", line 400, in raw_decode

**Comment by timchenxiaoyu** [comment]
maybe k8s version error。
 etcdctl ls /registry/thirdpartyresources
/registry/thirdpartyresources/network-policy.experimental.kubernetes.io


this network policy in thirdpartyresources

**Comment by timchenxiaoyu** [comment]
I run policy controller in docker,image is pull from docker hub.

**Comment by caseydavenport** [comment]
@timchenxiaoyu how are you configuring it? Are you using systemd? Running as a kubernetes pod?  Would be useful to see the exact manifest + options you're using to deploy it so I can help debug :)
