### ISSUE TITLE
policy-controller can not parse comma separated list of ETCD_ENDPOINTS

### ISSUE THREAD

**Issue by nilsher** [projectcalico/k8s-policy#88]
ETCD_ENDPOINTS=https://controller1.service.XXX.io:2379,https://controller2.service.XXX.io:2379,https://node1.service.XXX.io:2379

/dist # ./controller
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "handlers/network_policy.py", line 12, in <module>
  File "site-packages/pycalico/datastore.py", line 251, in __init__
  File "site-packages/etcd/client.py", line 202, in __init__
  File "site-packages/etcd/client.py", line 302, in machines
  File "site-packages/etcd/client.py", line 302, in machines
  File "site-packages/etcd/client.py", line 304, in machines
etcd.EtcdException: Could not get the list of servers, maybe you provided the wrong host(s) to connect to?
controller returned -1

It however works if I only assign one endpoint like 
ETCD_ENDPOINTS=https://controller1.service.XXX.io:2379

**Comment by nilsher** [comment]
Seems to be have been fixed in 0.5.4 was running 0.5.2
